var quotes = [
    ['Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.', 'Sherlock Holmes'],
    ['Darkness cannot drive out darkness, only light can do that. Hate cannot drive out hate, only love can do that.', 'Martin Luther King Jr.'],
    ['We can complain because rose bushes have thorns, or we can rejoice because thorn bushes have roses.', 'Abraham Lincoln'],
    ['I destroy my enemy when I make him my friend.', 'Abraham Lincoln'],
    ['Those who deny freedom to others deserve it not for themselves.', 'Abraham Lincoln'],
    ['I may walk slowly, but I never walk backwards.', 'Abraham Lincoln'],
    ['A lie told often enough becomes the truth.', 'Vladimir Lenin'],
    ['Success is not final, failure is not fatal; It is the courage to continue that counts.', 'Winston Churchill'],
    ['Conformity is the jailer of freedom and the enemy of truth.', 'John F. Kennedy'],
    ['The future belongs to those who prepare for it today.', 'Malcolm X'],
    ['Logic will get you from A to Z; Imagination will take you everywhere.', 'Albert Einstein'],
    ['Science without religion is lame, religion without science is blind.', 'Albert Einstein'],
    ['I have no special talents. I am only passionately curious.', 'Albert Einstein'],
    ['True definition of insanity is doing the same thing over and over again and expecting different results.', 'Albert Einstein'],
    ['Creativity is contagious, pass it on.', 'Albert Einstein'],
    ['Peace cannot be kept by force; It can only be achieved by understanding.', 'Albert Einstein'],
    ['I think and think for months and years. Ninety nine times out of a hundred I am wrong. The hundredth time I am right.', 'Albert Einstein'],
    ['Joy in looking and comprehending is natures most beautiful gift.', 'Albert Einstein'],
    ['Life isn\'t about finding yourself. Life is about creating yourself.', 'George Bernard Shaw'],
    ['Physics is much too hard for physicists.', 'David Hilbert'],
    ['The future depends on what we do in the present.', 'Mahatma Gandhi'],
    ['Those who know how to think need no teachers.', 'Mahatma Gandhi'],
    ['Strength does not come from physical capacity. It comes from an indomitable will.', 'Mahatma Gandhi'],
    ['In the practice of tolerance, one\'s enemy is the best teacher.', 'Dalai Lama'],
    ['I hated every minute of training, but I said, "suffer now and live the rest of your life as a champion".', 'Muhammad Ali'],
    ['Float like a butterfly, sting like a bee.', 'Muhammad Ali'],
    ['Every avalanche begins with the movement of a single snowflake. With each new project, my goal is to move a snowflake.', 'Thomas Frey'],
    ['The past is a ghost, the future a dream, and all we ever have is now.', 'Bill Cosby'],
    ['Have the courage to follow your heart and intuition. They somehow know what you truly want to become.', 'Steve Jobs'],
    ['We\'re here to put a dent in the universe. Otherwise why else even be here?', 'Steve Jobs'],
    ['I\'m convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.', 'Steve Jobs'],
    ['Your time is limited, so don\'t waste it living someone else\'s life.', 'Steve Jobs'],
    ['Have no fear of perfection, you\'ll never reach it.', 'Salvador Dali'],
    ['Knowing is not enough, we must apply. Willing is not enough, we must do.', 'Bruce Lee'],
    ['The principles of true art is not to portray, but to evoke.', 'Jerzy Kosinski'],
    ['If you do not express your own original ideas, if you do not listen to your own being, you will have betrayed yourself.', 'Rollo May'],
    ['Improve quality, you automatically improve productivity.', 'W. Edwards Deming'],
    ['The only real constant is change.', 'Author Unknown'],
    ['If today were the last day of your life, would you want to do what you are about to do today?', 'Author Unknown'],
    ['You miss 100% of the shots you don\'t take.', 'Author Unknown'],
    ['The problem is not the problem; the problem is your attitude about the problem.', 'Author Unknown'],
    ['Simplicity is the ultimate satisfaction.', 'Leonardo da Vince']

]

var quoteIndex = Math.floor(Math.random() * quotes.length);
var quote = document.getElementById('quote');
var quoteAuthor = document.getElementById('quoteAuthor');

quote.innerHTML = '"' + quotes[quoteIndex][0].toUpperCase() + '"';
quoteAuthor.innerHTML = '- ' + quotes[quoteIndex][1];

console.log(quotes.length);


function generateQuote() {
    quoteIndex = Math.floor(Math.random() * quotes.length);
    
    quote.innerHTML = '"' + quotes[quoteIndex][0].toUpperCase() + '"';
    quoteAuthor.innerHTML = '- ' + quotes[quoteIndex][1];
}













////////////////////////////////////////////////
///////////////////////////////////////////////
//////////////////////////////////////////////


//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],
//        ['', ''],

//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    [],
//    []


//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],
//    [,],